language: typescript
typescript:
  - "2.5.3"
branches:
   only:
      - master

before_script:
   - npm install
   - npm install -g firebase-tools
   - npm install -g @angular/cli

script:
   - ng build --prod --aot

after_success:
   - firebase deploy --token $FIREBASE_TOKEN
